### ISSUE TITLE
Schema et paramètres JLCPCB

### ISSUE THREAD

**Issue by pgille** [papsdroidfr/piClock#2]
Bonjour,

Merci pour ce projet
Vous serait-il possible d'ajouter :
- un schéma technique pour présenter le montage ? cela permettra de tester avant le montage
- des photos de votre montage (éléments électroniques soudés)
- les paramètres à saisir sur le site JLBPCB pour commander 

Merci beaucoup
cordialement

**Comment by papsdroidfr** [comment]
Bonsoir, merci. J'ai documenté directement le readme du Github avec les photos que j'ai prises à l'époque et les explications pour faire les soudures. Je mis à jour l'export Gerber avec un connecteur Jack beaucoup plus facile à trouver que celui que j'ai initialement imaginé: il s'agit d'un jack 3 points, c'est très standard. Au début je pensais prendre un barrel-jack 4 points mais c'est une vrai galère à trouver.

Côté soudure il n'y a vraiment aucun piège, juste penser à bien respecter le sens de la capacité.

Je vais bientôt faire un update pour proposer l'impression d'un boitier imprimé 3D, vu que je viens tout juste d’acquérir une imprimante 3D. Ca permettra de planquer les soudures et de rajouter une accroche pour la positionner sur un mur.

**Comment by pgille** [comment]
Bonjour,
Merci pour votre réponse.
Je souhaiterais commander la carte PCB mais je ne suis pas encore habitué à ce type de commande.
Il est demandé des paramètres pour le devis et la configuration : pourriez-vous les préciser svp pour que je puisse être sûr de commander une carte avec les bonnes préconisations (taille épaisseur, type de carte etc) ?
Par avance, merci beaucoup

**Comment by papsdroidfr** [comment]
En journée je fais un screenshots de jlcpcb. Mais c'est vraiment super simple car il faut laisser tous les paramètres par défaut proposés par jlcpcb sans rien toucher. Cliquer sur le premier choix  2 layers, uploader le gerber zippé, et tous les paramètres proposés par défaut ne doivent pas être modifié: il n'y a rien de particulier à faire de plus que ça.

**Comment by pgille** [comment]
Rebonjour,
C'est une première pour moi, d'où ma sollicitation : en faisant une première fois grâce à vos infos, cela me permettra de me former et de pouvoir refaire par la suite.
Cela me permettra de faire une première commande réussie en étant sûr que je suis sur les bons rails sur ce projet.
Merci encore pour vos réponses et vos projets que je vais suivre.
Mon 1er objectif est de créer cette piclock pour ma fille de 12 ans : cela faisait un moment que je papillonnais en cherchant le bon site avec les bonnes infos : du coup, j'ai déjà commandé des éléments hier soir et il me reste surtout cette carte PCB !
merci
