### ISSUE TITLE
câblage montage soudure

### ISSUE THREAD

**Issue by pgille** [papsdroidfr/piClock#3]
Bonjour,
Je vais sans aucun doute poser quelques questions stupides..., je m'en excuse par avance.

Je ne vois pas bien sur les photos dans le fichier readme.md comment / à quoi est connecté le connecteur JST femelle 3 points
Idem concernant le connecteur Jack femelle
Par ailleurs, quand vous écrivez : souder ensuite l'afficheur 7 segment directement sur son backpack avec les 5 pin header mâles comme expliqué sur le site d'Adafruit. Attention à ne pas vous tromper de sens
Avant de me tromper, je viens de regarder le site, mais quel sens faut -il bien prendre en compte ?
merci pour votre aide
Cordialement

**Comment by papsdroidfr** [comment]
le connecteur JST est à connecter aux 3 fils du ruban de leds: il y a un +5V, un GND et un fil SIG : les sérigraphies sur le PCB indiquent le raccordement à faire. Idem pour souder le backpack sur l'afficheur 7 segment Adafruit indique bien les sérigraphies à v&rifier pour s'assurer de ne pas le souder à l'envers.
